import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen font-[family-name:var(--font-geist-sans)] sm:w-3xl mx-auto">
          <main>{children}</main>
          <footer className="p-4 text-center text-xs text-gray-500">
            <p>ⓒ 2025. EJ n John All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
